debug: true
logging:
  level:
    com:
      ubiqube:
        etsi: DEBUG
    org:
      hibernate:
        SQL: INFO
      openstack4j: INFO
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLoggingListener: INFO
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure: 
        include: '*'
  info:
    git:
      mode: full

spring:
  application:
    name: mano-mon
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true



